# Generated by Django 6.0.2 on 2026-03-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=35, verbose_name="Телефон"),
        ),
    ]
